/*
 * Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
 * SPDX-License-Identifier: ISC
 */

#ifndef __EDMA_REGS__
#define __EDMA_REGS__

#define EDMA_GENMASK(end, start)	(uint32_t)((((uint64_t)1 << ((end) - (start) + 1)) - 1) << (start))

/*
 * EDMA Debug Statistics Macros
 */
#define EDMA_REG_BP_COUNTERS_NUM		18
#define EDMA_REG_PER_RING_TYPE_BP_COUNTER_MAX	6

#define EDMA_REG_TXCMPL_BP_IDX_OFFSET	0
#define EDMA_REG_RXDESC_BP_IDX_OFFSET	6
#define EDMA_REG_RXFILL_BP_IDX_OFFSET	12

#define EDMA_REG_BP_TXCMPL_RING_ID_OFFSET	0
#define EDMA_REG_BP_RXDESC_RING_ID_OFFSET	20
#define EDMA_REG_BP_RXFILL_RING_ID_OFFSET	44

/*
 * EDMA register offsets
 */
#define EDMA_REG_MAS_CTRL		0x0
#define EDMA_REG_PORT_CTRL		0x4
#define EDMA_REG_VLAN_CTRL		0x8
#define EDMA_REG_RXDESC2FILL_MAP_0	0x14
#define EDMA_REG_RXDESC2FILL_MAP_1	0x18
#define EDMA_REG_RXDESC2FILL_MAP_2	0x1c
#define EDMA_REG_RXDESC2FILL_MAP_3	0x100
#define EDMA_REG_RXDESC2FILL_MAP_4	0x104
#define EDMA_REG_RXDESC2FILL_MAP_5	0x108
#define EDMA_REG_TXQ_CTRL		0x20
#define EDMA_REG_TXQ_CTRL_2		0x24
#define EDMA_REG_TXQ_FC_0		0x28
#define EDMA_REG_TXQ_FC_1		0x30
#define EDMA_REG_TXQ_FC_2		0x34
#define EDMA_REG_TXQ_FC_3		0x38
#define EDMA_REG_RXQ_CTRL		0x3c
#define EDMA_REG_MISC_ERR_QID		0x40
#define EDMA_REG_RXQ_FC_THRE		0x44
#define EDMA_REG_DMAR_CTRL		0x48
#define EDMA_REG_AXIR_CTRL		0x4c
#define EDMA_REG_AXIW_CTRL		0x50
#define EDMA_REG_MIN_MSS		0x54
#define EDMA_REG_LOOPBACK_CTRL		0x58
#define EDMA_REG_MISC_INT_STAT		0x5c
#define EDMA_REG_MISC_INT_MASK		0x60
#define EDMA_REG_DBG_CTRL		0x64
#define EDMA_REG_DBG_DATA		0x68
#define EDMA_REG_DBG_DATA_MASK		0x7FFFFF	/* 23-bit mask */
#define EDMA_REG_DS_CMPL_ERR_DBG_VAL	0x409c		/* Debug control value for DS CMPL error */
#define EDMA_REG_DBG_CNT_TIME		0x1DC		/* Counter clock cycle for BP stats */
#define EDMA_REG_DBG_CNT_CLEAN		0x1E0		/* Bitmask[0:17] to clean specific BP counters */
#define EDMA_REG_DBG_TOTAL_GO		0x1E4		/* Enable/Disable BP counters */
#define EDMA_REG_DBG_TOTAL_CLEAN	0x1E8		/* Clean all BP counters */
#define EDMA_REG_DBG_CNT_TOTAL_CNT	0x1EC		/* Total BP count */

/*
 * EDMA debug counter bit fields
 */
#define EDMA_DBG_CNT_DUR_TIME_SHIFT	0
#define EDMA_DBG_CNT_DUR_TIME_MASK	EDMA_GENMASK(2, 0)		/* 3-bit mask */

#define EDMA_DBG_CNT_SINGLE_CLEAN_MASK	0x0003FFFFU 			/* 18-bit mask */

#define EDMA_DBG_CNT_TOTAL_GO_MASK	0x1U				/* 1-bit mask */
#define EDMA_DBG_CNT_TOTAL_CLEAN_MASK	0x1U				/* 1-bit mask */


/*
 * Debug counter port map registers
 * First register absolute addr: 0x2AE1B300
 * EDMA base is at 0x2AD00000, so relative offset = 0x11B300
 * There are 18 registers, 32-bit stride, value field uses lower 6 bits (0..63)
 */
#define EDMA_REG_DBG_CNT_PORT_MAP(n)	(0x11B300 + (0x4 * (n)))
#define EDMA_DBG_CNT_PORT_MAP_VAL_MASK	0x3FU				/* 6-bit mask */

/*
 * Debug BP counter registers
 * First register absolute addr: 0x2AE1B400
 * EDMA base is at 0x2AD00000, so relative offset = 0x11B400
 * There are 18 registers
 */
#define EDMA_REG_DBG_CNT_NUM(n)		(0x11B400 + (0x4 * (n)))
#define EDMA_REG_TX_TIMEOUT_THRESH	0x6c
#define EDMA_REG_REQ0_FIFO_THRESH	0x80
#define EDMA_REG_WB_OS_THRESH		0x84
#define EDMA_REG_MISC_ERR_QID_REG2	0x88
#define EDMA_REG_TXDESC2CMPL_MAP_0	0x8c
#define EDMA_REG_TXDESC2CMPL_MAP_1	0x90
#define EDMA_REG_TXDESC2CMPL_MAP_2	0x94
#define EDMA_REG_TXDESC2CMPL_MAP_3	0x98
#define EDMA_REG_TXCMPL_SEC_RING_REG	0x9c

#ifdef NSS_DP_MHT_SW_PORT_MAP
#define EDMA_MDIO_SLV_PASUE_MAP_0	0xA4
#define EDMA_MDIO_SLV_PASUE_MAP_1	0xA8

#if defined(NSS_DP_MDIO_HIGHER_VP_PORTS_SUPP)
#define EDMA_GLOBAL_MDIO_SLV_PAUSE_ID_REG0_MAX 0x8
#define EDMA_GLOBAL_MDIO_SLV_PAUSE_ID_REG1_MAX 0x8
#define EDMA_GLOBAL_MDIO_SLV_VPPORTS_MAX 0xF
#define EDMA_GLOBAL_MDIO_SLV_PAUSE_SHIFT	0x4
#else
#define EDMA_GLOBAL_MDIO_SLV_PAUSE_ID_REG0_MAX 0xa
#define EDMA_GLOBAL_MDIO_SLV_PAUSE_ID_REG1_MAX 0x6
#define EDMA_GLOBAL_MDIO_SLV_VPPORTS_MAX 0x7
#define EDMA_GLOBAL_MDIO_SLV_PAUSE_SHIFT	0x3
#endif

#define EDMA_GLOBAL_MDIO_SLV_PAUSE_ID_MAP_VPPORT(x, y) ((x) << (EDMA_GLOBAL_MDIO_SLV_PAUSE_SHIFT * y))
#endif

#if defined(CONFIG_IO_COHERENCY)
#define EDMA_REG_AXCACHE_OVERRIDE	0xac
#define EDMA_REG_CACHEINDEX_LUT		0xb0
#define EDMA_REG_CACHEINDEX_LUT2	0xb4
#endif

#if defined(NSS_DP_HIGHER_FC_CONFIG)
#define EDMA_REG_TXQ_FC_4		0xb8
#define EDMA_REG_TXQ_FC_5		0xc0
#define EDMA_REG_TXQ_FC_6		0xc4
#define EDMA_REG_TXQ_FC_7		0xc8
#endif

#if defined(NSS_DP_HW_GRO)
#define	EDMA_REG_SLOT_SEL(n)		(0x01C0 + (0x4 * (n)))
#define EDMA_REG_GRO_SLOT_VLD(n)	(0xFFB00 + ((n) * 0x10))
#define EDMA_REG_GRO_CONFIG1		0x01D0
#define EDMA_REG_GRO_CONFIG2		0x01D4
#endif

#define EDMA_REG_TXDESC_BA(n)		(0x1000 + (0x1000 * (n)))
#define EDMA_REG_TXDESC_PROD_IDX(n)	(0x1004 + (0x1000 * (n)))
#define EDMA_REG_TXDESC_CONS_IDX(n)	(0x1008 + (0x1000 * (n)))
#define EDMA_REG_TXDESC_RING_SIZE(n)	(0x100c + (0x1000 * (n)))
#define EDMA_REG_TXDESC_CTRL(n)		(0x1010 + (0x1000 * (n)))
#define EDMA_REG_TXDESC_BA2(n)		(0x1014 + (0x1000 * (n)))

#if defined(NSS_DP_HIGHMEM_SUPP)
#define EDMA_REG_TXDESC_BA_HIGH(n)	(0x1018 + (0x1000 * (n)))
#define EDMA_REG_TXDESC_BA2_HIGH(n)	(0x101C + (0x1000 * (n)))
#endif

#if defined(NSS_DP_RING_IDX_CONFIG)
#define EDMA_REG_TXDESC_UPLOAD_IDX_TRIG(n)	(0x1020 + (0x1000 * (n)))
#define EDMA_REG_TXDESC_UPLOAD_IDX_ADDR_L(n)	(0x1024 + (0x1000 * (n)))
#define EDMA_REG_TXDESC_UPLOAD_IDX_ADDR_H(n)	(0x1028 + (0x1000 * (n)))
#define EDMA_REG_TXDESC_DROP(n)			(0x102C + (0x1000 * (n)))

#define EDMA_REG_TXDESC_IDX_UNIT_SHIFT	10
#define EDMA_REG_TXDESC_IDX_UNIT_MASK	EDMA_GENMASK(11, 10)
#define EDMA_REG_TXDESC_IDX_UNIT(x)	(((x) << EDMA_REG_TXDESC_IDX_UNIT_SHIFT) & EDMA_REG_TXDESC_IDX_UNIT_MASK)

#define EDMA_REG_TXDESC_UP_IDX_ENABLE_SHIFT	8
#define EDMA_REG_TXDESC_UP_IDX_ENABLE		((0x1) << EDMA_REG_TXDESC_UP_IDX_ENABLE_SHIFT)
#endif

#define EDMA_REG_RXFILL_FORMAT(n)	(0x2903C + (0x100 * (n)))
#define EDMA_REG_RXFILL_BA(n)		(0x29000 + (0x100 * (n)))
#define EDMA_REG_RXFILL_PROD_IDX(n)	(0x29004 + (0x100 * (n)))
#define EDMA_REG_RXFILL_CONS_IDX(n)	(0x29008 + (0x100 * (n)))
#define EDMA_REG_RXFILL_RING_SIZE(n)	(0x2900c + (0x100 * (n)))
#define EDMA_REG_RXFILL_BUFFER1_SIZE(n)	(0x29010 + (0x100 * (n)))
#define EDMA_REG_RXFILL_FC_THRE(n)	(0x29014 + (0x100 * (n)))
#define EDMA_REG_RXFILL_UGT_THRE(n)	(0x29018 + (0x100 * (n)))
#define EDMA_REG_RXFILL_RING_EN(n)	(0x2901c + (0x100 * (n)))
#define EDMA_REG_RXFILL_DISABLE(n)	(0x29020 + (0x100 * (n)))
#define EDMA_REG_RXFILL_DISABLE_DONE(n)	(0x29024 + (0x100 * (n)))
#define EDMA_REG_RXFILL_INT_STAT(n)	(0x36000 + (0x1000 * (n)))
#define EDMA_REG_RXFILL_INT_MASK(n)	(0x36004 + (0x1000 * (n)))

#if defined(NSS_DP_HIGHMEM_SUPP)
#define EDMA_REG_RXFILL_BA_HIGH(n)	(0x29028 + (0x100 * (n)))
#endif

#if defined(NSS_DP_RING_IDX_CONFIG)
#define EDMA_REG_RXFILL_INDEX_RESET(n)	(0x2902C + (0x100 * (n)))
#define EDMA_REG_RXFILL_UPLOAD_IDX_TRIG(n)	(0x29030 + (0x100 * (n)))
#define EDMA_REG_RXFILL_UPLOAD_IDX_ADDR_L(n)	(0x29034 + (0x100 * (n)))
#define EDMA_REG_RXFILL_UPLOAD_IDX_ADDR_H(n)	(0x29038 + (0x100 * (n)))

#define EDMA_REG_RXFILL_IDX_UNIT_SHIFT	4
#define EDMA_REG_RXFILL_IDX_UNIT_MASK	EDMA_GENMASK(5, 4)
#define EDMA_REG_RXFILL_IDX_UNIT(x)	(((x) << EDMA_REG_RXFILL_IDX_UNIT_SHIFT) & EDMA_REG_RXFILL_IDX_UNIT_MASK)

#define EDMA_REG_RXFILL_UP_IDX_ENABLE_SHIFT	8
#define EDMA_REG_RXFILL_UP_IDX_ENABLE		(0x1UL << EDMA_REG_RXFILL_UP_IDX_ENABLE_SHIFT)

#endif

#define EDMA_REG_RXDESC_BA(n)		(0x4A000 + (0x100 * (n)))
#define EDMA_REG_RXDESC_PROD_IDX(n)	(0x4A004 + (0x100 * (n)))
#define EDMA_REG_RXDESC_CONS_IDX(n)	(0x4A008 + (0x100 * (n)))
#define EDMA_REG_RXDESC_RING_SIZE(n)	(0x4A00C + (0x100 * (n)))
#define EDMA_REG_RXDESC_FC_THRE(n)	(0x4A010 + (0x100 * (n)))
#define EDMA_REG_RXDESC_UGT_THRE(n)	(0x4A014 + (0x100 * (n)))
#define EDMA_REG_RXDESC_CTRL(n)		(0x4A018 + (0x100 * (n)))
#define EDMA_REG_RXDESC_BPC(n)		(0x4A01C + (0x100 * (n)))
#define EDMA_REG_RXDESC_DISABLE(n)	(0x4A020 + (0x100 * (n)))
#define EDMA_REG_RXDESC_DISABLE_DONE(n)	(0x4A024 + (0x100 * (n)))
#define EDMA_REG_RXDESC_PREHEADER_BA(n)	(0x4A028 + (0x100 * (n)))
#define EDMA_REG_RXDESC_RESET(n)	(0x4A034 + (0x100 * (n)))

#define EDMA_REG_RXDESC_INT_STAT(n)	(0x62000 + (0x100 * (n)))
#define EDMA_REG_RXDESC_INT_MASK(n)	(0x62004 + (0x100 * (n)))

#define EDMA_REG_RX_MOD_TIMER(n)	(0x62008 + (0x100 * (n)))
#define EDMA_REG_RX_INT_CTRL(n)		(0x6200C + (0x100 * (n)))

#if defined(NSS_DP_HIGHMEM_SUPP)
#define EDMA_REG_RXDESC_BA_HIGH(n)	(0x4a02C + (0x100 * (n)))
#define EDMA_REG_RXDESC_PREHEADER_BA_HIGH(n)		(0x4a030 + (0x100 * (n)))
#endif

#if defined(NSS_DP_RING_IDX_CONFIG)
#define EDMA_REG_RXDESC_INDEX_RESET(n)	(0x4a034 + (0x100 * (n)))
#define EDMA_REG_RXDESC_UPLOAD_IDX_TRIG(n)	(0x4a038 + (0x100 * (n)))
#define EDMA_REG_RXDESC_UPLOAD_IDX_ADDR_L(n)	(0x4a03C + (0x100 * (n)))
#define EDMA_REG_RXDESC_UPLOAD_IDX_ADDR_H(n)	(0x4a040 + (0x100 * (n)))

#define EDMA_REG_RXDESC_IDX_UNIT_SHIFT	4
#define EDMA_REG_RXDESC_IDX_UNIT_MASK	EDMA_GENMASK(5, 4)
#define EDMA_REG_RXDESC_IDX_UNIT(x)	(((x) << EDMA_REG_RXDESC_IDX_UNIT_SHIFT) & EDMA_REG_RXDESC_IDX_UNIT_MASK)
#define EDMA_REG_RXDESC_UIT_SHIFT	8
#define EDMA_REG_RXDESC_UP_IDX_TMR	25
#define EDMA_REG_RXDESC_UP_IDX_THRS	16

#define EDMA_REG_RXDESC_UP_IDX_TRG_VAL (((EDMA_REG_RXDESC_UP_IDX_TMR) << (EDMA_REG_RXDESC_UIT_SHIFT)) | EDMA_REG_RXDESC_UP_IDX_THRS)

#define EDMA_REG_RXDESC_UP_IDX_ENABLE_SHIFT	8
#define EDMA_REG_RXDESC_UP_IDX_ENABLE		((0x1) << EDMA_REG_RXDESC_UP_IDX_ENABLE_SHIFT)
#endif

#if defined(CONFIG_IO_COHERENCY)
#define EDMA_REG_RXDESC_CACHE(n)		(0x4a044 + (0x100 * (n)))
#endif

#define EDMA_REG_TXCMPL_BA(n)		(0x79000 + (0x1000 * (n)))
#define EDMA_REG_TXCMPL_PROD_IDX(n)	(0x79004 + (0x1000 * (n)))
#define EDMA_REG_TXCMPL_CONS_IDX(n)	(0x79008 + (0x1000 * (n)))
#define EDMA_REG_TXCMPL_RING_SIZE(n)	(0x7900c + (0x1000 * (n)))
#define EDMA_REG_TXCMPL_UGT_THRE(n)	(0x79010 + (0x1000 * (n)))
#define EDMA_REG_TXCMPL_CTRL(n)		(0x79014 + (0x1000 * (n)))
#define EDMA_REG_TXCMPL_BPC(n)		(0x79018 + (0x1000 * (n)))

#define EDMA_TXCMPL_IDX_RESET_SHIFT		2
#define EDMA_TXCMPL_IDX_RESET		(0x1 << EDMA_TXCMPL_IDX_RESET_SHIFT)

#if defined(NSS_DP_HIGHMEM_SUPP)
#define EDMA_REG_TXCMPL_BA_HIGH(n)	(0x7901C + (0x1000 * (n)))
#endif

#if defined(NSS_DP_RING_IDX_CONFIG)
#define EDMA_REG_TXCMPL_UPLOAD_IDX_TRIG(n)	(0x79020 + (0x1000 * (n)))
#define EDMA_REG_TXCMPL_UPLOAD_IDX_ADDR_L(n)	(0x79024 + (0x1000 * (n)))
#define EDMA_REG_TXCMPL_UPLOAD_IDX_ADDR_H(n)	(0x79028 + (0x1000 * (n)))

#define EDMA_REG_TXCMPL_IDX_UNIT_SHIFT	4
#define EDMA_REG_TXCMPL_IDX_UNIT_MASK	EDMA_GENMASK(5, 4)
#define EDMA_REG_TXCMPL_IDX_UNIT(x)	(((x) << EDMA_REG_TXCMPL_IDX_UNIT_SHIFT) & EDMA_REG_TXCMPL_IDX_UNIT_MASK)

#define EDMA_REG_TXCMPL_UP_IDX_SHIFT	8
#define EDMA_REG_TXCMPL_UP_IDX_ENABLE	(0x1UL << EDMA_REG_TXCMPL_UP_IDX_SHIFT)
#endif

#if defined(CONFIG_IO_COHERENCY)
#define EDMA_REG_TXCMPL_CACHE(n)		(0x7902C + (0x1000 * (n)))
#endif

#define EDMA_REG_TX_INT_STAT(n)		(0x99000 + (0x1000 * (n)))
#define EDMA_REG_TX_INT_MASK(n)		(0x99004 + (0x1000 * (n)))
#define EDMA_REG_TX_MOD_TIMER(n)	(0x99008 + (0x1000 * (n)))
#define EDMA_REG_TX_INT_CTRL(n)		(0x9900c + (0x1000 * (n)))

#define EDMA_RX_RING_ID_QUEUE0_SHIFT	0
#define EDMA_RX_RING_ID_QUEUE0_MASK	EDMA_GENMASK(7, 0)
#define EDMA_RX_RING_ID_QUEUE0_GET(x)	(((x) & EDMA_RX_RING_ID_QUEUE0_MASK) >> EDMA_RX_RING_ID_QUEUE0_SHIFT)
#define EDMA_RX_RING_ID_QUEUE0_SET(x)	(((x) << EDMA_RX_RING_ID_QUEUE0_SHIFT) & EDMA_RX_RING_ID_QUEUE0_MASK)
#define EDMA_RX_RING_ID_QUEUE0_RESET(x)	((x) & ~EDMA_RX_RING_ID_QUEUE0_MASK)

#define EDMA_RX_RING_ID_QUEUE1_SHIFT	8
#define EDMA_RX_RING_ID_QUEUE1_MASK	EDMA_GENMASK(15, 8)
#define EDMA_RX_RING_ID_QUEUE1_GET(x)	(((x) & EDMA_RX_RING_ID_QUEUE1_MASK) >> EDMA_RX_RING_ID_QUEUE1_SHIFT)
#define EDMA_RX_RING_ID_QUEUE1_SET(x)	(((x) << EDMA_RX_RING_ID_QUEUE1_SHIFT) & EDMA_RX_RING_ID_QUEUE1_MASK)
#define EDMA_RX_RING_ID_QUEUE1_RESET(x)	((x) & ~EDMA_RX_RING_ID_QUEUE1_MASK)

#define EDMA_RX_RING_ID_QUEUE2_SHIFT	16
#define EDMA_RX_RING_ID_QUEUE2_MASK	EDMA_GENMASK(23, 16)
#define EDMA_RX_RING_ID_QUEUE2_GET(x)	(((x) & EDMA_RX_RING_ID_QUEUE2_MASK) >> EDMA_RX_RING_ID_QUEUE2_SHIFT)
#define EDMA_RX_RING_ID_QUEUE2_SET(x)	(((x) << EDMA_RX_RING_ID_QUEUE2_SHIFT) & EDMA_RX_RING_ID_QUEUE2_MASK)
#define EDMA_RX_RING_ID_QUEUE2_RESET(x)	((x) & ~EDMA_RX_RING_ID_QUEUE2_MASK)

#define EDMA_RX_RING_ID_QUEUE3_SHIFT	24
#define EDMA_RX_RING_ID_QUEUE3_MASK	EDMA_GENMASK(31, 24)
#define EDMA_RX_RING_ID_QUEUE3_GET(x)	(((x) & EDMA_RX_RING_ID_QUEUE3_MASK) >> EDMA_RX_RING_ID_QUEUE3_SHIFT)
#define EDMA_RX_RING_ID_QUEUE3_SET(x)	(((x) << EDMA_RX_RING_ID_QUEUE3_SHIFT) & EDMA_RX_RING_ID_QUEUE3_MASK)
#define EDMA_RX_RING_ID_QUEUE3_RESET(x)	((x) & ~EDMA_RX_RING_ID_QUEUE3_MASK)

/*
 * EDMA_REG_PORT_CTRL register
 */
#define EDMA_PORT_PAD_EN			0x2
#define EDMA_PORT_EDMA_EN			0x4
#define EDMA_PORT_TX_DROP_EN			0x8

/*
 * EDMA_REG_TXQ_CTRL register
 */
#define EDMA_TXDESC_PF_THRE_MASK		0xf
#define EDMA_TXDESC_PF_THRE_SHIFT		0
#define EDMA_TXCMPL_WB_THRE_MASK		0xf
#define EDMA_TXCMPL_WB_THRE_SHIFT		4
#define EDMA_TXDESC_PKT_SRAM_THRE_MASK		0xff
#define EDMA_TXDESC_PKT_SRAM_THRE_SHIFT		8
#define EDMA_TXCMPL_WB_TIMER_MASK		0xffff
#define EDMA_TXCMPL_WB_TIMER_SHIFT		16

/*
 * EDMA_REG_TXQ_CTRL_2 register
 */
#define EDMA_GLOBAL_TSO_IDENT_UP_CTRL_MASK	(1 << 19)

/*
 * EDMA_REG_RXQ_CTRL register
 */
#define EDMA_RXFILL_PF_THRE_MASK		0xf
#define EDMA_RXFILL_PF_THRE_SHIFT		0
#define EDMA_RXDESC_WB_THRE_MASK		0xf
#define EDMA_RXDESC_WB_THRE_SHIFT		4
#define EDMA_RXDESC_WB_TIMER_MASK		0xffff
#define EDMA_RXDESC_WB_TIMER_SHIFT		16

/*
 * EDMA_REG_RX_TX_FULL_QID register
 */
#define EDMA_RX_DESC_FULL_QID_MASK		0xff
#define EDMA_RX_DESC_FULL_QID_SHIFT		0
#define EDMA_TX_CMPL_BUF_FULL_QID_MASK		0xff
#define EDMA_TX_CMPL_BUF_FULL_QID_SHIFT		8
#define EDMA_TX_SRAM_FULL_QID_MASK		0x1f
#define EDMA_TX_SRAM_FULL_QID_SHIFT		16

/*
 * EDMA_REG_RXQ_FC_THRE reister
 */
#define EDMA_RXFILL_FIFO_XOFF_THRE_MASK		0x1f
#define EDMA_RXFILL_FIFO_XOFF_THRE_SHIFT	0
#define EDMA_DESC_FIFO_XOFF_THRE_MASK		0x3f
#define EDMA_DESC_FIFO_XOFF_THRE_SHIFT		16
#define EDMA_GLOBAL_FLOW_IDX_CFG_MASK		0x1
#define EDMA_GLOBAL_FLOW_IDX_CFG_SHIFT		5

#define EDMA_GLOBAL_FLOW_IDX_CFG_SET(x)		(((x) & EDMA_GLOBAL_FLOW_IDX_CFG_MASK) \
						<< EDMA_GLOBAL_FLOW_IDX_CFG_SHIFT)

/*
 * EDMA_REG_DMAR_CTRL register
 */
#define EDMA_DMAR_REQ_PRI_MASK			0x7
#define EDMA_DMAR_REQ_PRI_SHIFT			0
#define EDMA_DMAR_BURST_LEN_MASK		0x1
#define EDMA_DMAR_BURST_LEN_SHIFT		3
#define EDMA_DMAR_TXDATA_OUTSTANDING_NUM_MASK	0x3f
#define EDMA_DMAR_TXDATA_OUTSTANDING_NUM_SHIFT	4
#define EDMA_DMAR_TXDESC_OUTSTANDING_NUM_MASK	0xf
#define EDMA_DMAR_TXDESC_OUTSTANDING_NUM_SHIFT	10
#define EDMA_DMAR_RXFILL_OUTSTANDING_NUM_MASK	0xf
#define EDMA_DMAR_RXFILL_OUTSTANDING_NUM_SHIFT	14

#define EDMA_DMAR_REQ_PRI_SET(x)		(((x) & EDMA_DMAR_REQ_PRI_MASK) \
						<< EDMA_DMAR_REQ_PRI_SHIFT)
#define EDMA_DMAR_TXDATA_OUTSTANDING_NUM_SET(x)	(((x) & EDMA_DMAR_TXDATA_OUTSTANDING_NUM_MASK) \
						<< EDMA_DMAR_TXDATA_OUTSTANDING_NUM_SHIFT)
#define EDMA_DMAR_TXDESC_OUTSTANDING_NUM_SET(x)	(((x) & EDMA_DMAR_TXDESC_OUTSTANDING_NUM_MASK) \
						<< EDMA_DMAR_TXDESC_OUTSTANDING_NUM_SHIFT)
#define EDMA_DMAR_RXFILL_OUTSTANDING_NUM_SET(x)	(((x) & EDMA_DMAR_RXFILL_OUTSTANDING_NUM_MASK) \
						<< EDMA_DMAR_RXFILL_OUTSTANDING_NUM_SHIFT)
#define EDMA_DMAR_BURST_LEN_SET(x)		(((x) & EDMA_DMAR_BURST_LEN_MASK) \
						<< EDMA_DMAR_BURST_LEN_SHIFT)

#define EDMA_BURST_LEN_ENABLE			0

/*
 * EDMA_REG_TX_TIMEOUT_THRESH register
 */
#define EDMA_TX_TIMEOUT_THRESH_VAL		0xFFFF

/*
 * EDMA RXDESC base address mask
 */
#define EDMA_RXDESC_BA_MASK			0xffffffff
#define EDMA_RXDESC_BA_HIGHER_MASK		0xff

/*
 * EDMA_LOOPBACK_CTRL register
 */
#define EDMA_REG_LOOPBACK_CMPL_SHIFT		24
#define EDMA_REG_LOOPBACK_DESC(x)		(1 << (x))
#define EDMA_REG_LOOPBACK_CMPL(x)		((1 << (x)) << EDMA_REG_LOOPBACK_CMPL_SHIFT)

/*
 * EDMA RXDESC pre-header base address mask
 */
#define EDMA_RXDESC_PREHEADER_BA_MASK		0xffffffff
#define EDMA_RXDESC_PREHEADER_BA_HIGHER_MASK	0xff

/*
 * EDMA_REG_AXIW_CTRL_REG
 */
#define EDMA_AXIW_MAX_WR_SIZE_EN		0x400

/*
 * EDMA DISABLE
 */
#define EDMA_DISABLE				0

#if defined(NSS_DP_HIGHER_RING_MASK_CONFIG)
/*
 * EDMA_REG_TXDESC_PROD_IDX register
 */
#define EDMA_TXDESC_PROD_IDX_MASK		0xffffffff

/*
 * EDMA_REG_TXDESC_CONS_IDX register
 */
#define EDMA_TXDESC_CONS_IDX_MASK		0xffffffff

/*
 * EDMA_REG_TXDESC_RING_SIZE register
 */
#define EDMA_TXDESC_RING_SIZE_MASK		0xffffffff
#else
/*
 * EDMA_REG_TXDESC_PROD_IDX register
 */
#define EDMA_TXDESC_PROD_IDX_MASK		0xffff

/*
 * EDMA_REG_TXDESC_CONS_IDX register
 */
#define EDMA_TXDESC_CONS_IDX_MASK		0xffff

/*
 * EDMA_REG_TXDESC_RING_SIZE register
 */
#define EDMA_TXDESC_RING_SIZE_MASK		0xffff
#endif

/*
 * EDMA_REG_TXDESC_CTRL register
 */
#define EDMA_TXDESC_TX_ENABLE			0x1

/*
 * EDMA_TXDESC_TX_RESET
 */
#define EDMA_TXDESC_TX_RESET_SHIFT		9
#define EDMA_TXDESC_TX_RESET			(0x1 << EDMA_TXDESC_TX_RESET_SHIFT)

#define EDMA_TXDESC_CTRL_TXEN_SHIFT		0
#define EDMA_TXDESC_CTRL_TXEN_MASK		EDMA_GENMASK(0, 0)
#define EDMA_TXDESC_CTRL_TXEN_GET(x)		(((x) & EDMA_TXDESC_CTRL_TXEN_MASK) >> EDMA_TXDESC_CTRL_TXEN_SHIFT)
#define EDMA_TXDESC_CTRL_TXEN_SET(x)		(((x) << EDMA_TXDESC_CTRL_TXEN_SHIFT) & EDMA_TXDESC_CTRL_TXEN_MASK)

/*
 * EDMA_REG_TXDESC_CTRL - TSO IDENT UPDATE CTRL field
 */
#define EDMA_TXDESC_TSO_IDENT_UPDATE_CTRL_SHIFT		13
#define EDMA_TXDESC_TSO_IDENT_UPDATE_CTRL_MASK		EDMA_GENMASK(14, 13)
#define EDMA_TXDESC_TSO_IDENT_UPDATE_CTRL_SET(x)	(((x) << EDMA_TXDESC_TSO_IDENT_UPDATE_CTRL_SHIFT) & EDMA_TXDESC_TSO_IDENT_UPDATE_CTRL_MASK)
#define EDMA_TXDESC_TSO_IDENT_UPDATE_BY_PARSER		3

#if defined(NSS_DP_HIGHER_FC_CONFIG)
#define EDMA_TXDESC_CTRL_FC_GRP_ID_SHIFT	1
#define EDMA_TXDESC_CTRL_FC_GRP_ID_MASK		EDMA_GENMASK(4, 1)
#define EDMA_TXDESC_CTRL_ARB_GRP_ID_SHIFT	5
#define EDMA_TXDESC_CTRL_ARB_GRP_ID_MASK	EDMA_GENMASK(6, 5)
#else
#define EDMA_TXDESC_CTRL_FC_GRP_ID_SHIFT	15
#define EDMA_TXDESC_CTRL_FC_GRP_ID_MASK		EDMA_GENMASK(19, 15)
#define EDMA_TXDESC_CTRL_ARB_GRP_ID_SHIFT	5
#define EDMA_TXDESC_CTRL_ARB_GRP_ID_MASK	EDMA_GENMASK(6, 5)
#endif

#define EDMA_TXDESC_CTRL_FC_GRP_ID_GET(x)	(((x) & EDMA_TXDESC_CTRL_FC_GRP_ID_MASK) >> EDMA_TXDESC_CTRL_FC_GRP_ID_SHIFT)
#define EDMA_TXDESC_CTRL_FC_GRP_ID_SET(x)	(((x) << EDMA_TXDESC_CTRL_FC_GRP_ID_SHIFT) & EDMA_TXDESC_CTRL_FC_GRP_ID_MASK)
#define EDMA_TXDESC_CTRL_ARB_GRP_ID_GET(x)	(((x) & EDMA_TXDESC_CTRL_ARB_GRP_ID_MASK) >> EDMA_TXDESC_CTRL_ARB_GRP_ID_SHIFT)
#define EDMA_TXDESC_CTRL_ARB_GRP_ID_SET(x)	(((x) << EDMA_TXDESC_CTRL_ARB_GRP_ID_SHIFT) & EDMA_TXDESC_CTRL_ARB_GRP_ID_MASK)

/*
 * EDMA TX ring mode (preheader/secondary ring) configurations
 */
#define EDMA_TXDESC_PH_EN	1
#define EDMA_TXDESC_CTRL_PH_EN_SHIFT		20
#define EDMA_TXDESC_CTRL_PH_EN_MASK		EDMA_GENMASK(20, 20)
#define EDMA_TXDESC_CTRL_PH_EN_GET(x)		(((x) & EDMA_TXDESC_CTRL_PH_EN_MASK) >> EDMA_TXDESC_CTRL_PH_EN_SHIFT)
#define EDMA_TXDESC_CTRL_PH_EN_SET(x)		(((x) << EDMA_TXDESC_CTRL_PH_EN_SHIFT) & EDMA_TXDESC_CTRL_PH_EN_MASK)



#if defined(NSS_DP_HIGHER_RING_MASK_CONFIG)
/*
 * EDMA_REG_TXCMPL_PROD_IDX register
 */
#define EDMA_TXCMPL_PROD_IDX_MASK		0xffffffff

/*
 * EDMA_REG_TXCMPL_CONS_IDX register
 */
#define EDMA_TXCMPL_CONS_IDX_MASK		0xffffffff

/*
 * EDMA_REG_TXCMPL_RING_SIZE register
 */
#define EDMA_TXCMPL_RING_SIZE_MASK		0xffffffff
#else
/*
 * EDMA_REG_TXCMPL_PROD_IDX register
 */
#define EDMA_TXCMPL_PROD_IDX_MASK		0xffff

/*
 * EDMA_REG_TXCMPL_CONS_IDX register
 */
#define EDMA_TXCMPL_CONS_IDX_MASK		0xffff

/*
 * EDMA_REG_TXCMPL_RING_SIZE register
 */
#define EDMA_TXCMPL_RING_SIZE_MASK		0xffff
#endif

/*
 * EDMA_REG_TXCMPL_UGT_THRE register
 */
#define EDMA_TXCMPL_LOW_THRE_MASK		0xffff
#define EDMA_TXCMPL_LOW_THRE_SHIFT		0
#define EDMA_TXCMPL_FC_THRE_MASK		0x3f
#define EDMA_TXCMPL_FC_THRE_SHIFT		16

/*
 * EDMA_REG_TXCMPL_CTRL register
 */
#define EDMA_TXCMPL_RET_MODE_BUFF_ADDR		0x0
#define EDMA_TXCMPL_RET_MODE_OPAQUE		0x1

/*
 * EDMA_REG_TX_MOD_TIMER register
 */
#define EDMA_TX_MOD_TIMER_INIT_MASK		0xffff
#define EDMA_TX_MOD_TIMER_INIT_SHIFT		0

/*
 * EDMA_REG_TX_INT_CTRL register
 */
#define EDMA_TX_INT_MASK			0x3

#if defined(NSS_DP_HIGHER_RING_MASK_CONFIG)
/*
 * EDMA_REG_RXFILL_PROD_IDX register
 */
#define EDMA_RXFILL_PROD_IDX_MASK		0xffffffff

/*
 * EDMA_REG_RXFILL_CONS_IDX register
 */
#define EDMA_RXFILL_CONS_IDX_MASK		0xffffffff

/*
 * EDMA_REG_RXFILL_RING_SIZE register
 */
#define EDMA_RXFILL_RING_SIZE_MASK		0xffffffff

/*
 * EDMA_RXFILL_RING_SIZE register
 */
#define EDMA_RXFILL_RING_SIZE(n)	EDMA_REG_RXFILL_BUFFER1_SIZE(n)
#else
/*
 * EDMA_REG_RXFILL_PROD_IDX register
 */
#define EDMA_RXFILL_PROD_IDX_MASK		0xffff

/*
 * EDMA_REG_RXFILL_CONS_IDX register
 */
#define EDMA_RXFILL_CONS_IDX_MASK		0xffff

/*
 * EDMA_REG_RXFILL_RING_SIZE register
 */
#define EDMA_RXFILL_RING_SIZE_MASK		0xffff

/*
 * EDMA_RXFILL_RING_SIZE register
 */
#define EDMA_RXFILL_RING_SIZE(n)	EDMA_REG_RXFILL_BUFFER1_SIZE(n)
#endif

/*
 * EDMA_REG_RXFILL_FC_THRE register
 */
#define EDMA_RXFILL_FC_XON_THRE_MASK		0x7ff
#define EDMA_RXFILL_FC_XON_THRE_SHIFT		12
#define EDMA_RXFILL_FC_XOFF_THRE_MASK		0x7ff
#define EDMA_RXFILL_FC_XOFF_THRE_SHIFT		0

/*
 * EDMA_REG_RXFILL_UGT_THRE register
 */
#define EDMA_RXFILL_LOW_THRE_MASK		0xffff
#define EDMA_RXFILL_LOW_THRE_SHIFT		0

/*
 * EDMA_REG_RXFILL_RING_EN register
 */
#define EDMA_RXFILL_RING_EN			0x1

/*
 * EDMA_REG_RXFILL_RING_DISABLE register
 */
#define EDMA_RXFILL_RING_DISABLE		0x1

/*
 * EDMA_REG_RXFILL_INT_MASK register
 */
#define EDMA_RXFILL_INT_MASK			0x1

#if defined(NSS_DP_HIGHER_RING_MASK_CONFIG)
/*
 * EDMA_REG_RXDESC_PROD_IDX register
 */
#define EDMA_RXDESC_PROD_IDX_MASK		0xffffffff

/*
 * EDMA_REG_RXDESC_CONS_IDX register
 */
#define EDMA_RXDESC_CONS_IDX_MASK		0xffffffff

/*
 * EDMA_REG_RXDESC_RING_SIZE register
 */
#define EDMA_RXDESC_RING_SIZE_MASK		0xffffffff
#else
/*
 * EDMA_REG_RXDESC_PROD_IDX register
 */
#define EDMA_RXDESC_PROD_IDX_MASK		0xffff

/*
 * EDMA_REG_RXDESC_CONS_IDX register
 */
#define EDMA_RXDESC_CONS_IDX_MASK		0xffff

/*
 * EDMA_REG_RXDESC_RING_SIZE register
 */
#define EDMA_RXDESC_RING_SIZE_MASK		0xffff
#define EDMA_RXDESC_PL_OFFSET_MASK		0x1ff
#define EDMA_RXDESC_PL_OFFSET_SHIFT		16
#define EDMA_RXDESC_PL_DEFAULT_VALUE		0
#endif

/*
 * EDMA_REG_RXDESC_FC_THRE register
 */
#define EDMA_RXDESC_FC_XON_THRE_MASK		0x7ff
#define EDMA_RXDESC_FC_XON_THRE_SHIFT		12
#define EDMA_RXDESC_FC_XOFF_THRE_MASK		0x7ff
#define EDMA_RXDESC_FC_XOFF_THRE_SHIFT		0

/*
 * EDMA_REG_RXDESC_UGT_THRE register
 */
#define EDMA_RXDESC_LOW_THRE_MASK		0xffff
#define EDMA_RXDESC_LOW_THRE_SHIFT		0

/*
 * EDMA_REG_RXDESC_CTRL register
 */
#define EDMA_RXDESC_MODE_DS			0x800
#define EDMA_RXDESC_WR_PH			BIT(10)
#define EDMA_RXDESC_STAG_REMOVE_EN		0x8
#define EDMA_RXDESC_CTAG_REMOVE_EN		0x4
#define EDMA_RXDESC_QDISC_EN			0x2
#define EDMA_RXDESC_RX_EN			0x1
#define EDMA_RXDESC_RX_DISABLE			0x1
#define EDMA_RXDESC_RX_RESET			0x1
#define EDMA_RXDESC_CTRL_PH_EN			(~(0x40))

/*
 * EDMA_RXFILL_RESET register
 */
#define EDMA_RXFILL_IDX_RESET			0x1
#define EDMA_REG_RXFILL_IDX_RESET(n)	(0x2902C + (0x100 * (n)))

/*
 * EDMA RX ring mode (preheader/secondary ring) configurations
 */
#define EDMA_RXDESC_PH_EN	1
#define EDMA_RXDESC_CTRL_PH_EN_SHIFT		10
#define EDMA_RXDESC_CTRL_PH_EN_MASK		EDMA_GENMASK(10, 10)
#define EDMA_RXDESC_CTRL_PH_EN_GET(x)		(((x) & EDMA_RXDESC_CTRL_PH_EN_MASK) >> EDMA_RXDESC_CTRL_PH_EN_SHIFT)
#define EDMA_RXDESC_CTRL_PH_EN_SET(x)		(((x) << EDMA_RXDESC_CTRL_PH_EN_SHIFT) & EDMA_RXDESC_CTRL_PH_EN_MASK)

#define EDMA_RXDESC_PH_PAYLOAD_OFFSET		32
#define EDMA_RXDESC_PAYLOAD_OFFSET_SHIFT	23
#define EDMA_RXDESC_PAYLOAD_OFFSET_MASK		EDMA_GENMASK(31, 23)
#define EDMA_RXDESC_PAYLOAD_OFFSET_GET(x)	(((x) & EDMA_RXDESC_PAYLOAD_OFFSET_MASK) >> EDMA_RXDESC_PAYLOAD_OFFSET_SHIFT)
#define EDMA_RXDESC_PAYLOAD_OFFSET_SET(x)	(((x) << EDMA_RXDESC_PAYLOAD_OFFSET_SHIFT) & EDMA_RXDESC_PAYLOAD_OFFSET_MASK)

/*
 * EDMA_REG_TX_INT_MASK register
 */
#define EDMA_TX_INT_MASK_PKT_INT		0x1
#define EDMA_TX_INT_MASK_UGT_INT		0x2

/*
 * EDMA_REG_RXDESC_INT_STAT register
 */
#define EDMA_RXDESC_INT_STAT_PKT_INT		0x1
#define EDMA_RXDESC_INT_STAT_UGT_INT		0x2

/*
 * EDMA_REG_RXDESC_INT_MASK register
 */
#define EDMA_RXDESC_INT_MASK_PKT_INT		0x1
#define EDMA_RXDESC_INT_MASK_TIMER_INT_DIS	0x2

#define EDMA_MASK_INT_DISABLE			0x0
#define EDMA_MASK_INT_CLEAR			0x0

/*
 * EDMA_REG_RX_MOD_TIMER register
 */
#define EDMA_RX_MOD_TIMER_INIT_MASK		0xffff
#define EDMA_RX_MOD_TIMER_INIT_SHIFT		0

/*
 * EDMA QID2RID register sizes
 */
#define EDMA_QID2RID_DEPTH			0x40
#define EDMA_QID2RID_QUEUES_PER_ENTRY		8

/*
 * TXDESC shift values
 */
#define EDMA_TXDESC_MORE_SHIFT			31
#define EDMA_TXDESC_TSO_EN_SHIFT		30
#define EDMA_TXDESC_PREHEADER_SHIFT		29
#define EDMA_TXDESC_POOL_ID_SHIFT		24
#define EDMA_TXDESC_POOL_ID_MASK		0x1f
#define EDMA_TXDESC_DATA_OFFSET_SHIFT		16
#define EDMA_TXDESC_DATA_OFFSET_MASK		0xff
#define EDMA_TXDESC_DATA_LENGTH_SHIFT		0
#define EDMA_TXDESC_DATA_LENGTH_MASK		0x1ffff

#define EDMA_RING_DMA_MASK			0xffffffff
#define EDMA_RING_DMA_HIGHER_MASK		0xff

/*
 * RXDESC shift values
 */
#define EDMA_RXDESC_RX_RXFILL_CNT_MASK		0x000f
#define EDMA_RXDESC_RX_RXFILL_CNT_SHIFT		16

#define EDMA_RXDESC_PKT_SIZE_MASK		0x3fff
#define EDMA_RXDESC_PKT_SIZE_SHIFT		0

#define EDMA_RXDESC_RXD_VALID_MASK		0x1
#define EDMA_RXDESC_RXD_VALID_SHIFT		31

#define EDMA_RXDESC_RING_INT_STATUS_MASK	0x3

#define EDMA_RING_DISABLE			0
#define EDMA_TXCMPL_RING_INT_STATUS_MASK	0x3
#define EDMA_TXCMPL_RETMODE_OPAQUE		0x0
#define EDMA_TXCMPL_DESC_MODE_8B		0x1
#define EDMA_RXFILL_RING_INT_STATUS_MASK	0x1

/*
 * TODO tune the timer and threshold values
 */
#define EDMA_RXFILL_FIFO_XOFF_THRE		0x3
#define EDMA_RXFILL_PF_THRE			0x3
#define EDMA_RXDESC_WB_THRE			0x0
#define EDMA_RXDESC_WB_TIMER			0x2

#define EDMA_RXDESC_XON_THRE			50
#define EDMA_RXDESC_XOFF_THRE			30
#define EDMA_RXDESC_LOW_THRE			0
#define EDMA_RX_MOD_TIMER_INIT			1000
#define EDMA_RX_NE_INT_EN			0x2

#define EDMA_TXDESC_PF_THRE			0x3
#define EDMA_TXCMPL_WB_THRE			0X0
#define EDMA_TXDESC_PKT_SRAM_THRE		0x20
#define EDMA_TXCMPL_WB_TIMER			0x2

#define EDMA_TX_MOD_TIMER			150

#define EDMA_TX_INITIAL_PROD_IDX		0x0
#define EDMA_TX_NE_INT_EN			0x2

/*
 * EDMA misc error mask
 */
#define EDMA_MISC_AXI_RD_ERR_MASK		0x1
#define EDMA_MISC_AXI_WR_ERR_MASK		0x2
#define EDMA_MISC_RX_DESC_FIFO_FULL_MASK	0x4
#define EDMA_MISC_RX_ERR_BUF_SIZE_MASK		0x8
#define EDMA_MISC_TX_SRAM_FULL_MASK		0x10
#define EDMA_MISC_TX_CMPL_BUF_FULL_MASK		0x20
#define EDMA_MISC_DATA_LEN_ERR_MASK		0x40
#define EDMA_MISC_TX_TIMEOUT_MASK		0x80
#define EDMA_MISC_PASS_THR_ERR_FWD_MASK		0x100
#define EDMA_MISC_TXQ_PASSTHR_OFFSET_MIS_MASK	0x200
#define EDMA_MISC_TXQ_DS_CMPL_ERR_MASK		0x400

/*
 * EDMA txdesc2cmpl map
 */
#define EDMA_TXDESC2CMPL_MAP_TXDESC_MASK	0x1F
#define EDMA_TXDESC2CMPL_MAP_NUM_IN_SINGLE_REG	6
#define EDMA_TXDESC2CMPL_MAP_TXDESC_ID_BIT_COUNT	5

/*
 * EDMA rxdesc2fill map
 */
#define EDMA_RXDESC2FILL_MAP_PRI_VLD_FLAG	0x40
#define EDMA_RXDESC2FILL_MAP_SEC_VLD_FLAG	0x20
#define EDMA_RXDESC2FILL_MAP_RXDESC_MASK	0x1f

#define EDMA_RXFILL_FORMAT_16B		1
#define EDMA_RXFILL_FORMAT_8B		0

#define EDMA_RXFILL_FORMAT_SHIFT	0
#define EDMA_RXFILL_FORMAT_MASK		0x1
#define EDMA_RXFILL_FORMAT_SET(x)	(((x) << EDMA_RXFILL_FORMAT_SHIFT) & EDMA_RXFILL_FORMAT_MASK)

#if defined(NSS_DP_HW_GRO)
#define EDMA_RXDESC_GRO_INFO_SHIFT	12
#define EDMA_RXDESC_GRO_INFO_MASK	EDMA_GENMASK(15, 12)
#define EDMA_RXDESC_GRO_INFO_GET(x)	(((x) & EDMA_RXDESC_GRO_INFO_MASK) >> EDMA_RXDESC_GRO_INFO_SHIFT)

#define EDMA_RXDESC_GRO_EN_FIN_MASK	0x1
#define EDMA_RXDESC_GRO_EN_PSH_MASK	0x2
#define EDMA_RXDESC_GRO_EN_MORE_MASK	0x4
#define EDMA_RXDESC_GRO_EN		0x8


#define EDMA_REG_GRO_CONFIG1_BUF_LEN_MASK	0x1FFFF
#define EDMA_REG_GRO_CONFIG1_BUF_LEN_SHIFT	9

#define EDMA_REG_GRO_CONFIG1_DESC_COUNT_MASK	0x3F
#define EDMA_REG_GRO_CONFIG1_DESC_COUNT_SHIFT	3

#define EDMA_REG_GRO_CONFIG1_BUF_LEN_SET(x)	(((x) & EDMA_REG_GRO_CONFIG1_BUF_LEN_MASK) << EDMA_REG_GRO_CONFIG1_BUF_LEN_SHIFT)
#define EDMA_REG_GRO_CONFIG1_DESC_COUNT_SET(x)	(((x) & EDMA_REG_GRO_CONFIG1_DESC_COUNT_MASK) << EDMA_REG_GRO_CONFIG1_DESC_COUNT_SHIFT)

#define EDMA_REG_GRO_CONFIG1_BUF_LEN_GET(x)	(((x) >> EDMA_REG_GRO_CONFIG1_BUF_LEN_SHIFT) & EDMA_REG_GRO_CONFIG1_BUF_LEN_MASK)
#define EDMA_REG_GRO_CONFIG1_DESC_COUNT_GET(x)	(((x) >> EDMA_REG_GRO_CONFIG1_DESC_COUNT_SHIFT) & (EDMA_REG_GRO_CONFIG1_DESC_COUNT_MASK))

#define EDMA_GRO_SLOT_VAL_ENABLE	0xFF
#endif

/*
 * DDRQ
 */
#define EDMA_REG_DDRQ_AC_QUEUE_CFG_TBL(n)	(0xF8000 + (0x20 * (n)))
#define EDMA_REG_DDRQ_AC_GRP_CFG_TBL(n)		(0xFA200 + (0x10 * (n)))
//#define EDMA_REG_DDRQ_AC_GRP_SHRD_CNT_CFG_TBL(n)	(0xFC500 + (0x10 * (n)))
#define EDMA_REG_DDRQ_GBL_CFG_OFFSET		(0x00140)
#define EDMA_REG_DDRQ_RX_DATA_BASE_ADDR_L_OFFSET	(0x00134)
#define EDMA_REG_DDRQ_RX_DESC_BASE_ADDR_L_OFFSET	(0x00138)
#define EDMA_REG_DDRQ_RX_BASE_ADDR_H_OFFSET	(0x0013C)
#define EDMA_REG_DDRQ_DATA_OFFSET_REG0_OFFSET	(0x158)
#define EDMA_REG_DDRQ_DATA_OFFSET_REG1_OFFSET	(0x15C)

#define EDMA_REG_DDRQ_VIRTUAL_PORT_ID_MASK	0x1F
#define EDMA_REG_DDRQ_VIRTUAL_PORT_TBL_OFFSET(n)	(0x11B000 + (0x4 * (n)))

#define EDMA_REG_DDRQ_DBG_CNT_BYTE_PKT_CTR_OFFSET	(0x00220)
#define EDMA_REG_DDRQ_DBG_CNT_THRESHOLD_OFFSET(n)	(0x11C000 + (0x40 * (n)))
#define EDMA_REG_DDRQ_DBG_CNT_STATS_OFFSET(n)		(0x140000 + (0x80 * (n)))
#define	EDMA_REG_DDRQ_DBG_CNT_BYTE_PKT_STATUS_OFFSET(n)		(0x001FC + (0x4*n))

#define EDMA_REG_DDRQ_LINKLIST_INI_EN_SHIFT	16
#define EDMA_REG_DDRQ_LINKLIST_INI_EN		(1 << EDMA_REG_DDRQ_LINKLIST_INI_EN_SHIFT)

#define EDMA_REG_DDRQ_DESC_BLK_BASE_ADDR_H_SHIFT	8
#define EDMA_REG_DDRQ_DESC_BLK_BASE_ADDR_H_MASK	EDMA_GENMASK(15, 8)
#define EDMA_REG_DDRQ_DESC_BLK_BASE_ADDR_H_GET(x)	(((x) & EDMA_REG_DDRQ_DESC_BLK_BASE_ADDR_H_MASK) >> EDMA_REG_DDRQ_DESC_BLK_BASE_ADDR_H_SHIFT)
#define EDMA_REG_DDRQ_DESC_BLK_BASE_ADDR_H_SET(x)	(((x) << EDMA_REG_DDRQ_DESC_BLK_BASE_ADDR_H_SHIFT) & EDMA_REG_DDRQ_DESC_BLK_BASE_ADDR_H_MASK)

#define EDMA_REG_DDRQ_DATA_BLK_BASE_ADDR_H_SHIFT	0
#define EDMA_REG_DDRQ_DATA_BLK_BASE_ADDR_H_MASK	EDMA_GENMASK(7, 0)
#define EDMA_REG_DDRQ_DATA_BLK_BASE_ADDR_H_GET(x)	(((x) & EDMA_REG_DDRQ_DATA_BLK_BASE_ADDR_H_MASK) >> EDMA_REG_DDRQ_DATA_BLK_BASE_ADDR_H_SHIFT)
#define EDMA_REG_DDRQ_DATA_BLK_BASE_ADDR_H_SET(x)	(((x) << EDMA_REG_DDRQ_DATA_BLK_BASE_ADDR_H_SHIFT) & EDMA_REG_DDRQ_DATA_BLK_BASE_ADDR_H_MASK)

#define EDMA_REG_DDRQ_GBL_EN_SHIFT	4
#define EDMA_REG_DDRQ_GBL_EN_MASK	EDMA_GENMASK(4, 4)
#define EDMA_REG_DDRQ_GBL_EN_GET(x)	(((x) & EDMA_REG_DDRQ_GBL_EN_MASK) >> EDMA_REG_DDRQ_GBL_EN_SHIFT)
#define EDMA_REG_DDRQ_GBL_EN_SET(x)	(((x) << EDMA_REG_DDRQ_GBL_EN_SHIFT) & EDMA_REG_DDRQ_GBL_EN_MASK)


#define EDMA_REG_DDRQ_DESC_PF_THRES_SHIFT	10
#define EDMA_REG_DDRQ_DESC_PF_THRES_MASK	EDMA_GENMASK(14, 10)
#define EDMA_REG_DDRQ_DESC_PF_THRES_GET(x)	(((x) & EDMA_REG_DDRQ_DESC_PF_THRES_MASK) >> EDMA_REG_DDRQ_DESC_PF_THRES_SHIFT)
#define EDMA_REG_DDRQ_DESC_PF_THRES_SET(x)	(((x) << EDMA_REG_DDRQ_DESC_PF_THRES_SHIFT) & EDMA_REG_DDRQ_DESC_PF_THRES_MASK)


#define EDMA_REG_DDRQ_PKT_DATA_ALIGN_SHIFT	9
#define EDMA_REG_DDRQ_PKT_DATA_ALIGN_MASK	EDMA_GENMASK(9, 9)
#define EDMA_REG_DDRQ_PKT_DATA_ALIGN_GET(x)	(((x) & EDMA_REG_DDRQ_PKT_DATA_ALIGN_MASK) >> EDMA_REG_DDRQ_PKT_DATA_ALIGN_SHIFT)
#define EDMA_REG_DDRQ_PKT_DATA_ALIGN_SET(x)	(((x) << EDMA_REG_DDRQ_PKT_DATA_ALIGN_SHIFT) & EDMA_REG_DDRQ_PKT_DATA_ALIGN_MASK)

#define EDMA_REG_DDRQ_DATA_OFFSET_SHIFT		8
#define EDMA_REG_DDRQ_DATA_OFFSET_MASK	EDMA_GENMASK(8, 8)
#define EDMA_REG_DDRQ_DATA_OFFSET_GET(x)	(((x) & EDMA_REG_DDRQ_DATA_OFFSET_MASK) >> EDMA_REG_DDRQ_DATA_OFFSET_SHIFT)
#define EDMA_REG_DDRQ_DATA_OFFSET_SET(x)	(((x) << EDMA_REG_DDRQ_DATA_OFFSET_SHIFT) & EDMA_REG_DDRQ_DATA_OFFSET_MASK)

#define EDMA_REG_DDRQ_BLK_NUM_CFG_SHIFT		6
#define EDMA_REG_DDRQ_BLK_NUM_CFG_MASK		EDMA_GENMASK(7, 6)
#define EDMA_REG_DDRQ_BLK_NUM_CFG_GET(x)	(((x) & EDMA_REG_DDRQ_BLK_NUM_CFG_MASK) >> EDMA_REG_DDRQ_BLK_NUM_CFG_SHIFT)
#define EDMA_REG_DDRQ_BLK_NUM_CFG_SET(x)	(((x) << EDMA_REG_DDRQ_BLK_NUM_CFG_SHIFT) & EDMA_REG_DDRQ_BLK_NUM_CFG_MASK)

#define EDMA_REG_DDRQ_BLK_SIZE_CFG_SHIFT	4
#define EDMA_REG_DDRQ_BLK_SIZE_CFG_MASK	EDMA_GENMASK(5, 4)
#define EDMA_REG_DDRQ_BLK_SIZE_CFG_GET(x)	(((x) & EDMA_REG_DDRQ_BLK_SIZE_CFG_MASK) >> EDMA_REG_DDRQ_BLK_SIZE_CFG_SHIFT)
#define EDMA_REG_DDRQ_BLK_SIZE_CFG_SET(x)	(((x) << EDMA_REG_DDRQ_BLK_SIZE_CFG_SHIFT) & EDMA_REG_DDRQ_BLK_SIZE_CFG_MASK)

#define EDMA_REG_DDRQ_DESC_WB_THRES_SHIFT	0
#define EDMA_REG_DDRQ_DESC_WB_THRES_MASK	EDMA_GENMASK(3, 0)
#define EDMA_REG_DDRQ_DESC_WB_THRES_GET(x)	(((x) & EDMA_REG_DDRQ_DESC_WB_THRES_MASK) >> EDMA_REG_DDRQ_DESC_WB_THRES_SHIFT)
#define EDMA_REG_DDRQ_DESC_WB_THRES_SET(x)	(((x) << EDMA_REG_DDRQ_DESC_WB_THRES_SHIFT) & EDMA_REG_DDRQ_DESC_WB_THRES_MASK)

#define EDMA_REG_DDRQ_DATA_OFFSET_REG0_CFG_SHIFT	0
#define EDMA_REG_DDRQ_DATA_OFFSET_REG0_CFG_MASK		EDMA_GENMASK(11, 0)
#define EDMA_REG_DDRQ_DATA_OFFSET_REG0_CFG_GET(x)	(((x) & EDMA_REG_DDRQ_DATA_OFFSET_REG0_CFG_MASK) >> EDMA_REG_DDRQ_DATA_OFFSET_REG0_CFG_SHIFT)
#define EDMA_REG_DDRQ_DATA_OFFSET_REG0_CFG_SET(x)	(((x) << EDMA_REG_DDRQ_DATA_OFFSET_REG0_CFG_SHIFT) & EDMA_REG_DDRQ_DATA_OFFSET_REG0_CFG_MASK)

#define EDMA_REG_DDRQ_DATA_OFFSET_REG1_CFG_SHIFT	12
#define EDMA_REG_DDRQ_DATA_OFFSET_REG1_CFG_MASK		EDMA_GENMASK(23, 12)
#define EDMA_REG_DDRQ_DATA_OFFSET_REG1_CFG_GET(x)	(((x) & EDMA_REG_DDRQ_DATA_OFFSET_REG1_CFG_MASK) >> EDMA_REG_DDRQ_DATA_OFFSET_REG1_CFG_SHIFT)
#define EDMA_REG_DDRQ_DATA_OFFSET_REG1_CFG_SET(x)	(((x) << EDMA_REG_DDRQ_DATA_OFFSET_REG1_CFG_SHIFT) & EDMA_REG_DDRQ_DATA_OFFSET_REG1_CFG_MASK)

#define EDMA_REG_DDRQ_DATA_OFFSET_REG2_CFG_SHIFT	0
#define EDMA_REG_DDRQ_DATA_OFFSET_REG2_CFG_MASK		EDMA_GENMASK(11, 0)
#define EDMA_REG_DDRQ_DATA_OFFSET_REG2_CFG_GET(x)	(((x) & EDMA_REG_DDRQ_DATA_OFFSET_REG2_CFG_MASK) >> EDMA_REG_DDRQ_DATA_OFFSET_REG2_CFG_SHIFT)
#define EDMA_REG_DDRQ_DATA_OFFSET_REG2_CFG_SET(x)	(((x) << EDMA_REG_DDRQ_DATA_OFFSET_REG2_CFG_SHIFT) & EDMA_REG_DDRQ_DATA_OFFSET_REG2_CFG_MASK)

#define EDMA_REG_DDRQ_DATA_OFFSET_REG3_CFG_SHIFT	12
#define EDMA_REG_DDRQ_DATA_OFFSET_REG3_CFG_MASK		EDMA_GENMASK(23, 12)
#define EDMA_REG_DDRQ_DATA_OFFSET_REG3_CFG_GET(x)	(((x) & EDMA_REG_DDRQ_DATA_OFFSET_REG3_CFG_MASK) >> EDMA_REG_DDRQ_DATA_OFFSET_REG3_CFG_SHIFT)
#define EDMA_REG_DDRQ_DATA_OFFSET_REG3_CFG_SET(x)	(((x) << EDMA_REG_DDRQ_DATA_OFFSET_REG3_CFG_SHIFT) & EDMA_REG_DDRQ_DATA_OFFSET_REG3_CFG_MASK)

#define EDMA_REG_LP_FC_GRP_ID_MASK	0x1f
#define EDMA_REG_LP_FC_REG0	0x19C
#define EDMA_REG_LP_FC_REG1	0x1A0
#define EDMA_REG_LP_FC_REG2	0x1A4

#define EDMA_REG_DDRQ_ENQ_DIS_REG0_OFFSET	0x250
#define EDMA_REG_DDRQ_ENQ_DIS_REG1_OFFSET	0x254
#define EDMA_REG_DDRQ_ENQ_DIS_REG2_OFFSET	0x258
#define EDMA_REG_DDRQ_ENQ_DIS_REG3_OFFSET	0x268
#define EDMA_REG_DDRQ_ENQ_DIS_REG4_OFFSET	0x26C
#define EDMA_REG_DDRQ_ENQ_DIS_REG5_OFFSET	0x27C

#define EDMA_REG_DDRQ_DEQ_DROP_REG0_OFFSET	0x300
#define EDMA_REG_DDRQ_DEQ_DROP_REG1_OFFSET	0x304
#define EDMA_REG_DDRQ_DEQ_DROP_REG2_OFFSET	0x308
#define EDMA_REG_DDRQ_DEQ_DROP_REG3_OFFSET	0x30C
#define EDMA_REG_DDRQ_DEQ_DROP_REG4_OFFSET	0x310
#define EDMA_REG_DDRQ_DEQ_DROP_REG5_OFFSET	0x314

#define EDMA_DDRQ_DBG_CNT_BYTE_PKT_CLEAN_SET	1
#define EDMA_REG_DDRQ_DBG_CNT_BYTE_PKT_CLEAN_SHIFT	1
#define EDMA_REG_DDRQ_DBG_CNT_BYTE_PKT_CLEAN_MASK	EDMA_GENMASK(1, 1)
#define EDMA_REG_DDRQ_DBG_CNT_BYTE_PKT_CLEAN_GET(x)	(((x) & EDMA_REG_DDRQ_DBG_CNT_BYTE_PKT_CLEAN_MASK) >> EDMA_REG_DDRQ_DBG_CNT_BYTE_PKT_CLEAN_SHIFT)
#define EDMA_REG_DDRQ_DBG_CNT_BYTE_PKT_CLEAN_SET(x)	(((x) << EDMA_REG_DDRQ_DBG_CNT_BYTE_PKT_CLEAN_SHIFT) & EDMA_REG_DDRQ_DBG_CNT_BYTE_PKT_CLEAN_MASK)

#define EDMA_DDRQ_DBG_CNT_BYTE_PKT_GO_START	1
#define EDMA_DDRQ_DBG_CNT_BYTE_PKT_GO_STOP	0
#define EDMA_REG_DDRQ_DBG_CNT_BYTE_PKT_GO_SHIFT	0
#define EDMA_REG_DDRQ_DBG_CNT_BYTE_PKT_GO_MASK	EDMA_GENMASK(0, 0)
#define EDMA_REG_DDRQ_DBG_CNT_BYTE_PKT_GO_GET(x)	(((x) & EDMA_REG_DDRQ_DBG_CNT_BYTE_PKT_GO_MASK) >> EDMA_REG_DDRQ_DBG_CNT_BYTE_PKT_GO_SHIFT)
#define EDMA_REG_DDRQ_DBG_CNT_BYTE_PKT_GO_SET(x)	(((x) << EDMA_REG_DDRQ_DBG_CNT_BYTE_PKT_GO_SHIFT) & EDMA_REG_DDRQ_DBG_CNT_BYTE_PKT_GO_MASK)
#endif	/* __EDMA_REGS__ */
